/*
==========================
1 >> DB STRUCTURE EXPLORING
==========================
*/
-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all COLUMNS in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'



/*
==========================
2 >> DIMENSION EXPLORING
==========================
*/
-- EXPLORE ALL COUNTRIES OUR CUSTOMER COME FROM
SELECT DISTINCT country FROM gold.dim_customers

-- EXPLORE ALL CATEGORIES "THE MAJOR DIVISIONS"
SELECT DISTINCT category FROM gold.dim_products
SELECT DISTINCT category , subcategory FROM gold.dim_products
SELECT DISTINCT category , subcategory , product_name FROM gold.dim_products ORDER BY 1,2,3



/*
==========================
3 >> DATE EXPLORING
==========================
*/
-- FIND THE DATE OF THE FIRST AND LAST ORDER
SELECT MIN(order_date),
MAX(order_date),
DATEDIFF(YEAR ,MIN(order_date) , MAX(order_date))
FROM gold.fact_sales

-- FIND THE YOUNGEST AND OLDEST CUSTOMER
SELECT MIN(birthdate) oldest_customer,
DATEDIFF(YEAR ,MIN(birthdate) , GETDATE() ) oldest_age,
MAX(birthdate) youngest_customer,
DATEDIFF(YEAR ,MAX(birthdate) , GETDATE() ) youngest_age
FROM gold.dim_customers



/*
==========================
4 >> MEASURE EXPLORING
==========================
*/
-- FIND THE TOTAL SALES
SELECT SUM(sales_amount) FROM gold.fact_sales

-- FIND HOW MANY ITEMS ARE SOLD
SELECT SUM(quantity) FROM gold.fact_sales

-- FIND THE AVERAGE SELLING PRICE
SELECT AVG(price) FROM gold.fact_sales

-- FIND THE TOTAL NUMBER OF ORDERS 
SELECT COUNT(DISTINCT order_number) FROM gold.fact_sales

-- FIND THE TOTAL NUMBER OF PRODUCTS 
SELECT COUNT(DISTINCT product_number) FROM gold.dim_products

-- FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT  COUNT(customer_number) FROM gold.dim_customers
SELECT  COUNT(DISTINCT customer_number) FROM gold.dim_customers

-- FIND THE TOTAL NUMBER OF CUSTOMERS THAT HAS PLACED AN ORDER
SELECT COUNT(customer_key)
FROM gold.fact_sales

-- GENERATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value  FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' , SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' , AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Number of Orders' , COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Number of Products' , COUNT(DISTINCT product_number) FROM gold.dim_products
UNION ALL
SELECT 'Number of Customers' , COUNT(customer_number) FROM gold.dim_customers


/*
==========================
5 >> MAGNITUDE ANALYSIS
==========================
*/
-- FIND TOTAL CUSTOMERS BY COUNTRIES
SELECT  country , COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC
-- FIND TOTAL CUSTOMERS BY GENDER
-- FIND TOTAL PRODUCTS BY CATEGORY


-- WHAT IS THE AVERAGE COSTS IN EACH CATEGORY?
SELECT category,
AVG (cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost desc


-- WHAT IS THE TOTAL REVENUE GENERATED FOR EACH CATEGORY?
SELECT p.category,
SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON  s.product_key = p.product_key 
GROUP BY p.category
ORDER BY total_sales desc
-- FIND TOTAL REVENUE GENERATED BY EACH CUSTOMER


-- WHAT IS THE DISTRIBUTION OF SOLD ITEMS (QUANTITY) ACROSS COUNTRIES
SELECT c.country, 
SUM(s.quantity) AS sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key  = c.customer_key
GROUP BY c.country
ORDER BY sold_items DESC

/*
==========================
6 >> RANKING ANALYSIS
==========================
*/
-- WHICH 5 PRODUCTS GENERATED THE HIGHEST REVENUE ?
	-- GROUP BY
	-- WINDOW FUNCTION

SELECT *
FROM
(SELECT p.product_name,
SUM(s.sales_amount) AS revenue,
ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount)  DESC) AS rank_
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name)t
WHERE rank_  <= 5

-- WHAT ARE THE 5 WORST-PERFORMANCE PRODUCTS IN TERMS OF SALES?
SELECT *
FROM
(SELECT p.product_name,
SUM(s.sales_amount) AS revenue,
ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount)  ASC) AS rank_
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name)t
WHERE rank_  <= 5


